### ISSUE TITLE
Resurface a random tweet saved in your graph

### ISSUE THREAD

**Issue by 8bitgentleman** [dvargas92495/SmartBlocks#220]
# THIS IS BROKEN

## 📋 Describe the SmartBlock
This smartblock will resurface a random tweet that you have saved in your graph.

## ✅ Describe any prerequisites or dependencies that are required for this SmartBlock
None

**Comment by bjburch** [comment]
Got it installed and it looks like your image but nothing happens when I run it.

**Comment by 8bitgentleman** [comment]
@bjburch github messed up the formatting somehow. I've added a JSON import which should be correct.
